Refactor/save bench to file
MaverickTse/SigContrastFastAviUtl pull request #10
Opened 2016-10-30 10:55 UTC by yumetodo

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/yumetodo">@yumetodo</a> そもそもrender時benchmarkをOFFに方がいい。更新が早すぎてcrashの可能性もある</p>&mdash; 全くCloudFlareは最高だぜ (@MaverickTse) <a href="https://twitter.com/MaverickTse/status/792643345340329984">2016年10月30日</a></blockquote>

ということでファイルに書き出すpatch

2016-10-30 11:34 UTC, MaverickTse requested changes
Need to consider effect on HDD health. as this is frequent writing with little data, very much the same as BT clients in early days.

2016-10-30 11:34 UTC, MaverickTse commented on SigColorFastAviUtl/sigcolorfastaviutl.cpp
> +		logfile << "SDeCon," + elapsed_ns << std::endl;
This will write to the diskdrive every 10ms or so and only writing a few byte... not good for HDD health (this is like the BT clients in early days without sufficient buffering...). Can you modify it so that:
* initially write to a buffer
* write out the buffer when it reach 4KB size or on file/program close

Also, your log file implementation need to associate with a new checkbox on the UI. 

For the current implementation, I'll try finding if any function to disable the benchmark on its own when rendering to file.

2016-10-30 14:30 UTC, yumetodo commented
@MaverickTse changed to stop io when process video.

2016-10-30 14:45 UTC, MaverickTse commented
I said you need a NEW checkbox, not removing the title bar display!!!
That means set CHECK_N to 6 and add a new label for it.
I have already added a function to disable the benchmark checkbox when saving, so don't wipe it out.

2016-10-30 14:55 UTC, yumetodo commented
>not removing the title bar display!!!

!?

...I was missed 

>Also, your log file implementation need to associate with a new checkbox on the UI.

this. I'm trying to fix this.

2016-10-30 14:59 UTC, MaverickTse commented
take your time, no rush, don't work overnight

2016-10-31 04:36 UTC, yumetodo commented
![image](https://cloud.githubusercontent.com/assets/10869046/19844312/d0371f1a-9f6e-11e6-92a5-af4aa01751bb.png)
なんで``WM_COMMAND``が来てかつ``wparam``が``50344749``のときに``func_WndProc_con``がコケるんだ・・・？なんか影響のある変更したっけか

2016-10-31 05:20 UTC, MaverickTse commented
>なんでWM_COMMANDが来てかつwparamが50344749のときにfunc_WndProc_conがコケるんだ・・・？なんか影響のある変更したっけか

I'm also experiencing strange error. Previously, I tried adding an extra value to 
`int		check_default[] = { 1, 0, 0, 0 };`
then AviUtl crash immediately on startup :-\

Maybe `FILTER_DLL**  GetFilterTableList(void)` has bug, I'm not sure.

Anyway, try keeping check_defaut to 4 items and see if the error goes away.

2016-10-31 05:22 UTC, yumetodo commented
I think use config file to enable benchmark is best way. How do you think?

2016-10-31 05:29 UTC, MaverickTse commented
Just submitted a new patch. Try again.

2016-10-31 07:06 UTC, yumetodo commented
fixed!

2016-10-31 07:23 UTC, merged

2016-10-31 07:23 UTC, MaverickTse commented
お疲れ様でした　👍